# Generated by Django 4.2.6 on 2023-11-06 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SingleTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SingleIntegerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('options', models.ManyToManyField(to='emails.optionchoice')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='EmailField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.EmailField(max_length=254)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.emailtemplate')),
            ],
        ),
    ]
