# Generated by Django 4.2.6 on 2023-11-06 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_userproject'),
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailfield',
            name='template',
        ),
        migrations.RemoveField(
            model_name='multiplechoicefield',
            name='template',
        ),
        migrations.RemoveField(
            model_name='singleintegerfield',
            name='template',
        ),
        migrations.RemoveField(
            model_name='singletextfield',
            name='template',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='template',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='emailFields',
            field=models.ManyToManyField(blank=True, to='emails.emailfield'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='multipleChoiceFields',
            field=models.ManyToManyField(blank=True, to='emails.multiplechoicefield'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='singleIntegerFields',
            field=models.ManyToManyField(blank=True, to='emails.singleintegerfield'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='singleTextFields',
            field=models.ManyToManyField(blank=True, to='emails.singletextfield'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='textFields',
            field=models.ManyToManyField(blank=True, to='emails.textfield'),
        ),
    ]
