# Generated by Django 4.2.6 on 2023-11-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_remove_optionchoice_value_emailfield_placeholder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singletextfield',
            name='placeholder',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
