# Generated by Django 4.2.6 on 2023-11-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_singletextfield_placeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleTextField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('placeholder', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='emailFields',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='singleIntegerFields',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='singleTextFields',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='textFields',
        ),
        migrations.DeleteModel(
            name='EmailField',
        ),
        migrations.DeleteModel(
            name='SingleIntegerField',
        ),
        migrations.DeleteModel(
            name='SingleTextField',
        ),
        migrations.DeleteModel(
            name='TextField',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='simpleTextFields',
            field=models.ManyToManyField(blank=True, to='emails.simpletextfield'),
        ),
    ]
