# Generated by Django 4.2.6 on 2023-11-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_simpletextfield_remove_emailtemplate_emailfields_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionchoice',
            old_name='placeholder',
            new_name='option',
        ),
    ]
