# Generated by Django 4.2.6 on 2023-11-08 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0008_emailtemplate_created_at_emailtemplate_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('placeholder_value', models.CharField(max_length=75)),
                ('type', models.CharField(choices=[('simple', 'Simple Text Field'), ('multiple_choice', 'Multiple Choice Field'), ('text', 'Full Text Field')], max_length=15)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_placeholder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='simpletextfield',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='simpletextfield',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='multipleChoiceFields',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='simpleTextFields',
        ),
        migrations.DeleteModel(
            name='MultipleChoiceField',
        ),
        migrations.DeleteModel(
            name='SimpleTextField',
        ),
        migrations.AddField(
            model_name='placeholder',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholders', to='emails.emailtemplate'),
        ),
        migrations.AddField(
            model_name='placeholder',
            name='options',
            field=models.ManyToManyField(blank=True, to='emails.optionchoice'),
        ),
        migrations.AddField(
            model_name='placeholder',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_placeholder', to=settings.AUTH_USER_MODEL),
        ),
    ]
