# Generated by Django 4.2.6 on 2023-11-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_placeholder_remove_simpletextfield_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeholder',
            name='position',
        ),
    ]
