# Generated by Django 4.2.7 on 2023-11-03 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('case_number', models.IntegerField()),
                ('tid_number', models.IntegerField()),
                ('case_number_provided', models.BooleanField(default=False)),
                ('offered_additional_assistance', models.BooleanField(default=False)),
                ('case_notes', models.TextField(max_length=2000)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
