# Generated by Django 4.2.7 on 2023-11-03 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='agent_id',
            new_name='agent',
        ),
    ]
