# Generated by Django 4.2.7 on 2023-11-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_agent_id_note_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='additional_customer_information',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='case_notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='case_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='tid_number',
            field=models.IntegerField(blank=True),
        ),
    ]
